/* streams.js */

const streams = [
{"date": "2023/12/20", 
"title": "【＃歌枠｜縦型配信】初めての縦型で久しぶりに歌うよ！！", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=0s", 
"songs": [
{"name": "MIRA", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=5m37s"}, 
{"name": "ヲズワルド", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=12m50s"}, 
{"name": "グッバイ宣言", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=20m57s"}, 
{"name": "絶え間なく藍色", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=26m34s"}, 
{"name": "惑星ループ", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=32m57s"}, 
{"name": "私は、私達は", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=39m6s"}, 
{"name": "テレキャスタービーボーイ", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=45m55s"}, 
{"name": "アニマル", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=51m48s"}, 
{"name": "flos", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=57m12s"}, 
{"name": "三日月ステップ", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=1h4m4s"}, 
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=1h10m14s"}, 
{"name": "ニュートンダンス", "url": "https://www.youtube.com/watch?v=raW9zDr-frM&t=1h19m26s"}]}, 
{"date": "2024/02/04", 
"title": "【#歌枠｜#KARAOKE】プロセカ収録曲でルーレット歌枠❕", 
"theme": ["横枠","耐久","告知","プロセカ"], 
"url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=0s", 
"songs": [
{"name": "ドーナツホール", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=7m34s"}, 
{"name": "エンヴィーベイビー", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=14m36s"}, 
{"name": "群青讃歌", "type": "1番のみ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=21m54s"}, 
{"name": "ガランド", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=25m58s"}, 
{"name": "ベノム", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=31m25s"}, 
{"name": "トリコロージュ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=39m13s"}, 
{"name": "ヒバナ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=46m17s"}, 
{"name": "キュートなカノジョ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=53m13s"}, 
{"name": "脱法ロック", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=58m14s"}, 
{"name": "Awake Now", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h4m50s"}, 
{"name": "ボッカデラベリタ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h11m17s"}, 
{"name": "リアライズ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h18m11s"}, 
{"name": "サンドリヨン", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h23m29s"}, 
{"name": "アイドル親衛隊", "type": "1番のみ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h30m28s"}, 
{"name": "ミライ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h34m52s"}, 
{"name": "モア！ジャンプ！モア！", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h41m24s"}, 
{"name": "夜明けと蛍", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h46m36s"}, 
{"name": "お気に召すまま", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=1h54m45s"}, 
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h4m24s"}, 
{"name": "ウミユリ海底譚", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h10m34s"}, 
{"name": "アイデンティティ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h16m48s"}, 
{"name": "ビターチョコデコレーション", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h23m48s"}, 
{"name": "エゴロック", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h31m37s"}, 
{"name": "フィクサー", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h37m0s"}, 
{"name": "にっこり^^調査隊のテーマ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h43m31s"}, 
{"name": "ロキ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h49m26s"}, 
{"name": "砂の惑星", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=2h55m45s"}, 
{"name": "悪魔の踊り方", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=3h3m37s"}, 
{"name": "仮死化", "type": "配信途切れ", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=3h10m55s"}, 
{"name": "RAD DOGS", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=3h14m7s"}, 
{"name": "Iなんです", "url": "https://www.youtube.com/watch?v=8eecmnSH2O8&t=3h20m35s"}]}, 
{"date": "2024/02/28", 
"title": "【#歌枠 ｜#karaoke 】初見さん大歓迎❕アニソン歌枠✨", 
"theme": ["横枠","アニソン"], 
"url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=0s", 
"songs": [
{"name": "Sign", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=4m54s"}, 
{"name": "ピースサイン", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=12m14s"}, 
{"name": "プライド革命", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=21m8s"}, 
{"name": "花になって", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=27m50s"}, 
{"name": "ミックスナッツ", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=35m7s"}, 
{"name": "ウタカタララバイ", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=48m52s"}, 
{"name": "逆夢", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h1m8s"}, 
{"name": "アイドル", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h12m42s"}, 
{"name": "トウキョウ・シャンディ・ランデヴ", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h19m52s"}, 
{"name": "残響散歌", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h27m5s"}, 
{"name": "炎", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h32m9s"}, 
{"name": "勇者", "type": "1番のみ", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h40m45s"}, 
{"name": "1・2・3", "url": "https://www.youtube.com/watch?v=6mtgg8u35Zo&t=1h45m45s"}]}, 
{"date": "2024/04/24", 
"title": "【#歌枠｜#KARAOKE】めんへら・病み曲うたうよ❤️‍🩹🎀", 
"theme": ["横枠","病み"], 
"url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=0s", 
"songs": [
{"name": "キュートなカノジョ", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=5m36s"}, 
{"name": "ロウワー", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=10m16s"}, 
{"name": "カプリスキャスト", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=15m52s"}, 
{"name": "ラビットホール", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=21m47s"}, 
{"name": "ダーリンダンス", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=27m58s"}, 
{"name": "ド屑", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=34m46s"}, 
{"name": "キャットラビング", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=39m49s"}, 
{"name": "ザムザ", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=44m42s"}, 
{"name": "Love it?", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=58m23s"}, 
{"name": "メンヘラじゃないもん！", "url": "https://www.youtube.com/watch?v=udB_HK0rdmM&t=1h4m14s"}]}, 
{"date": "2024/05/12", 
"title": "【デビュー半年記念】12時間配信❕歌ってゲームして喋る！！", 
"theme": ["横枠","耐久"], 
"url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=0s", 
"songs": [
{"name": "StaRt", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=3m6s"}, 
{"name": "絶え間なく藍色", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=13m1s"}, 
{"name": "馬と鹿", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=20m55s"}, 
{"name": "混沌ブギ", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=30m24s"}, 
{"name": "オーバーライド", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=38m15s"}, 
{"name": "ロストワンの号哭", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=48m36s"}, 
{"name": "アンドロイドガール", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=57m8s"}, 
{"name": "ハイド・アンド・シーク", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=1h10m28s"}, 
{"name": "リアライズ", "url": "https://www.youtube.com/watch?v=sK-_gwd0rhk&t=1h16m35s"}]}, 
{"date": "2024/05/31", 
"title": "【#歌枠｜#KARAOKE】米津玄師(HACHI)さん縛り歌枠🎙️", 
"theme": ["横枠", "米津玄師"], 
"url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=0s", 
"songs": [
{"name": "パンダヒーロー", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=6m5s"}, 
{"name": "灰色と青", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=15m35s"}, 
{"name": "KICK BACK", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=25m15s"}, 
{"name": "orion", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=33m50s"}, 
{"name": "LOSER", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=42m30s"}, 
{"name": "ドーナツホール", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=50m50s"}, 
{"name": "マトリョシカ", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=58m27s"}, 
{"name": "馬と鹿", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=1h6m55s"}, 
{"name": "Flamingo", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=1h15m8s"}, 
{"name": "砂の惑星", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=1h23m44s"}, 
{"name": "アイネクライネ", "url": "https://www.youtube.com/watch?v=OOuftgON28Y&t=1h30m45s"}]}, 
{"date": "2024/06/03", 
"title": "【#歌枠｜#縦型】ゆるお歌枠🫧アカペラあり/リクエスト◎", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=0s", 
"songs": [
{"name": "鬼ノ宴", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=15m21s"}, 
{"name": "逆夢", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=20m35s"}, 
{"name": "fake face dance music", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=32m8s"}, 
{"name": "晩餐歌", "type": ["アカペラ "," 最初のみ"], "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=36m18s"}, 
{"name": "回る空うさぎ", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=42m3s"}, 
{"name": "Pretender", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=47m35s"}, 
{"name": "ダウナーウィッチ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=52m40s"}, 
{"name": "WILD CARD", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h0m49s"}, 
{"name": "虚ろを仰ぐ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h11m3s"}, 
{"name": "デスぺレート", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h16m32s"}, 
{"name": "ステラ", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h22m20s"}, 
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h27m45s"}, 
{"name": "ベノム", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h35m24s"}, 
{"name": "夜に駆ける", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h42m34s"}, 
{"name": "人マニア", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h46m57s"}, 
{"name": "猫猫的宇宙論", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h52m24s"}, 
{"name": "アイディスマイル", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=1h59m48s"}, 
{"name": "再生", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=2h5m20s"}, 
{"name": "Beat Eater", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=2h12m27s"}, 
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=D78_mmv4_XM&t=2h20m54s"}]}, 
{"date": "2024/06/15", 
"title": "【#歌枠】ゆるお歌枠🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=0s", 
"songs": [
{"name": "お気に召すまま", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=9m16s"}, 
{"name": "雨とペトラ", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=15m38s"}, 
{"name": "レディーレ", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=21m38s"}, 
{"name": "ドライフラワー", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=34m17s"}, 
{"name": "ベテルギウス", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=39m15s"}, 
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=44m43s"}, 
{"name": "Stellar Stellar", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=49m38s"}, 
{"name": "III", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=58m14s"}, 
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h10m58s"}, 
{"name": "マフィア", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h20m22s"}, 
{"name": "ラビットホール", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h24m48s"}, 
{"name": "スロウダウナー", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h31m31s"}, 
{"name": "ヴァンパイア", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h38m48s"}, 
{"name": "アンヘル", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h44m56s"}, 
{"name": "寝起きヤシの木", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h51m52s"}, 
{"name": "フォニイ", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=1h56m55s"}, 
{"name": "アイドル", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=2h2m15s"}, 
{"name": "花になって", "url": "https://www.youtube.com/watch?v=P6OGEe6t9GY&t=2h9m1s"}]}, 
{"date": "2024/07/07－１", 
"title": "【#歌枠】久々ゆるうた", 
"theme": ["横枠","分割", "七夕"], 
"url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=0s", 
"songs": [
{"name": "睨めっ娘", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=9m5s"}, 
{"name": "はいよろこんで", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=13m26s"}, 
{"name": "ホシアイ", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=20m18s"}, 
{"name": "ウミユリ海底譚", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=27m49s"}, 
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=34m20s"}, 
{"name": "オーバーライド", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=40m9s"}, 
{"name": "Flyer!", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=44m51s"}, 
{"name": "怪獣の花唄", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=53m49s"}, 
{"name": "ラヴカ？", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=1h2m14s"}, 
{"name": "III", "type": ["ミュート "," 途中まで"], "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=1h8m52s"}, 
{"name": "III", "type": "続きから", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=1h12m22s"}, 
{"name": "青と夏", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=1h18m39s"}, 
{"name": "StaRt", "type": "途中で配信終了", "url": "https://www.youtube.com/watch?v=8KMpxaF_Pmg&t=1h23m55s"}]}, 
{"date": "2024/07/07－２", 
"title": "【#歌枠】久々ゆるうた", 
"theme": ["横枠","分割", "七夕"], 
"url": "https://www.youtube.com/watch?v=hR1f5KjCUpk&t=0s", 
"songs": [
{"name": "ボルテッカー", "type": ["アカペラ "," エコーなし"], "url": "https://www.youtube.com/watch?v=hR1f5KjCUpk&t=11m9s"}, 
{"name": "偽物人間40号", "url": "https://www.youtube.com/watch?v=hR1f5KjCUpk&t=24m41s"}]}, 
{"date": "2024/07/18", 
"title": "【#歌枠｜#KARAOKE】Kanariaさん縛り歌枠♢", 
"theme": ["横枠","Kanaria"], 
"url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=0s", 
"songs": [
{"name": "エンヴィーベイビー", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=6m40s"}, 
{"name": "MIRA", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=11m48s"}, 
{"name": "KING", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=19m34s"}, 
{"name": "QUEEN", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=26m26s"}, 
{"name": "EYE", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=38m46s"}, 
{"name": "アイデンティティ", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=47m20s"}, 
{"name": "酔いどれ知らず", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=59m26s"}, 
{"name": "デーモンロード", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=1h7m2s"}, 
{"name": "大脳的なランデブー", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=1h13m20s"}, 
{"name": "レクイエム", "url": "https://www.youtube.com/watch?v=imlwibe4iQM&t=1h17m33s"}]}, 
{"date": "2024/07/28", 
"title": "【#歌枠｜#KARAOKE】夏曲多めにまったり歌ってしゃべる", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=0s", 
"songs": [
{"name": "ウミユリ海底譚", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=7m3s"}, 
{"name": "夏祭り", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=19m40s"}, 
{"name": "打上花火", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=25m58s"}, 
{"name": "いかないで", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=37m37s"}, 
{"name": "君の知らない物語", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h2m32s"}, 
{"name": "ブルーアンビエンスfeat.asmi", "type": "1番のみ", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h10m43s"}, 
{"name": "フロムトーキョー", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h14m50s"}, 
{"name": "サインはB", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h21m6s"}, 
{"name": "少女レイ", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h27m19s"}, 
{"name": "群像夏", "url": "https://www.youtube.com/watch?v=uiNR1FpTF9o&t=1h35m20s"}]}, 
{"date": "2024/08/06", 
"title": "【#歌枠｜#KARAOKE】懐かしのボカロ多めで歌います", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=0s", 
"songs": [
{"name": "マトリョシカ", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=16m14s"}, 
{"name": "メルト", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=26m18s"}, 
{"name": "レディーレ", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=31m53s"}, 
{"name": "DOGLAND", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=41m5s"}, 
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=46m14s"}, 
{"name": "夜咄ディセイブ", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=52m58s"}, 
{"name": "チルドレンレコード", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h0m27s"}, 
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h7m27s"}, 
{"name": "ローリンガール", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h16m40s"}, 
{"name": "アンノウン・マザーグース", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h22m55s"}, 
{"name": "CH4NGE", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h36m49s"}, 
{"name": "Mela!", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h44m41s"}, 
{"name": "独りんぼエンヴィー", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=1h52m26s"}, 
{"name": "Blessing", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h3m11s"}, 
{"name": "ドナーソング", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h10m17s"}, 
{"name": "アスノヨゾラ哨戒班", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h17m7s"}, 
{"name": "ノンブレス・オブリージュ", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h21m49s"}, 
{"name": "い～やい～やい～や", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h29m52s"}, 
{"name": "ブリキノダンス", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h36m6s"}, 
{"name": "ゴーストルール", "type": "最初アカペラ", "url": "https://www.youtube.com/watch?v=X-pL_IvADOI&t=2h42m55s"}]}, 
{"date": "2024/08/08", 
"title": "【#歌枠｜#KARAOKE】夜のしっとりバラード歌枠", 
"theme": ["横枠","バラード"], 
"url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=0s", 
"songs": [
{"name": "灰色と青", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=9m20s"}, 
{"name": "RAIN", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=17m17s"}, 
{"name": "きらり", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=26m40s"}, 
{"name": "スパークル", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=35m29s"}, 
{"name": "なんでもないや", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=43m58s"}, 
{"name": "ひまわりの約束", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=54m52s"}, 
{"name": "アイネクライネ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h3m15s"}, 
{"name": "orion", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h12m35s"}, 
{"name": "たばこ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h19m46s"}, 
{"name": "花に亡霊", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h37m53s"}, 
{"name": "晩餐歌", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h45m12s"}, 
{"name": "夜明けと蛍", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h52m8s"}, 
{"name": "回る空うさぎ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=1h59m53s"}, 
{"name": "secret base～君がくれたもの～", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h11m3s"}, 
{"name": "ハロ／ハワユ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h20m20s"}, 
{"name": "心做し", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h29m21s"}, 
{"name": "再会", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h36m20s"}, 
{"name": "打上花火", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h44m1s"}, 
{"name": "逆夢", "type": "最初アカペラ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=2h54m1s"}, 
{"name": "Stellar Stellar", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h2m27s"}, 
{"name": "宿命", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h13m39s"}, 
{"name": "Pretender", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h19m22s"}, 
{"name": "虚ろを扇ぐ", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h28m56s"}, 
{"name": "ダーリン", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h33m51s"}, 
{"name": "Overdose", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=3h38m5s"}, 
{"name": "群青", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=4h3m19s"}, 
{"name": "炎", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=4h13m56s"}, 
{"name": "Connectiong", "url": "https://www.youtube.com/watch?v=R3GmU9uige4&t=4h32m26s"}]}, 
{"date": "2024/08/25", 
"title": "【#歌枠｜#KARAOKE】落ち着く声のゆるゆる短め歌枠🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=0s", 
"songs": [
{"name": "はいよろこんで", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=7m7s"}, 
{"name": "フラジール", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=12m20s"}, 
{"name": "フィクサー", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=18m53s"}, 
{"name": "エゴロック", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=25m41s"}, 
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=31m41s"}, 
{"name": "ラヴィ", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=36m20s"}, 
{"name": "人マニア", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=42m15s"}, 
{"name": "ファイトソング", "type": "練習", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=46m50s"}, 
{"name": "ドラマツルギー", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=52m22s"}, 
{"name": "LOSER", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=59m31s"}, 
{"name": "ノンブレス・オブリージュ", "url": "https://www.youtube.com/watch?v=6N-96RezNKc&t=1h6m33s"}]}, 
{"date": "2024/09/28", 
"title": "【#歌枠｜#KARAOKE】土曜お昼のまったり歌枠🫧初見さん＆ROM専さん大歓迎～！", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=0s", 
"songs": [
{"name": "きらり", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=5m25s"}, 
{"name": "睨めっ娘", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=12m55s"}, 
{"name": "ファタール", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=20m30s"}, 
{"name": "月陽", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=27m58s"}, 
{"name": "花になって", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=35m27s"}, 
{"name": "フォニイ", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=46m1s"}, 
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=57m37s"}, 
{"name": "愛包ダンスホール", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h2m49s"}, 
{"name": "Loveit?", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h12m51s"}, 
{"name": "ラブカ?", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h17m50s"}, 
{"name": "ヒアソビ", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h27m18s"}, 
{"name": "ハイド・アンド・シーク", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h41m37s"}, 
{"name": "アニマル", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h52m19s"}, 
{"name": "砂の惑星", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=1h59m25s"}, 
{"name": "ニュートンダンス", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=2h6m52s"}, 
{"name": "天才ロック", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=2h12m18s"}, 
{"name": "Fighting My Way", "type": "配信途切れ", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=2h21m19s"}, 
{"name": "Fighting My Way", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=2h32m14s"}, 
{"name": "侵蝕", "url": "https://www.youtube.com/watch?v=PznDcEK0iS4&t=2h39m8s"}]}, 
{"date": "2024/10/12", 
"title": "【#歌枠｜#KARAOKE】誕生日なので大好きなGigaさんの曲をたくさん歌います！！✨", 
"theme": ["横枠","Giga"], 
"url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=0s", 
"songs": [
{"name": "G4L", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=14m11s"}, 
{"name": "劣等上等", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=18m32s"}, 
{"name": "ULTRA C", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=24m39s"}, 
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=29m57s"}, 
{"name": "熱愛フローズン", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=38m1s"}, 
{"name": "drop pop candy", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=45m4s"}, 
{"name": "GETCHA!", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=54m1s"}, 
{"name": "CH4NGE", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=59m46s"}, 
{"name": "Fighting My Way", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=1h6m18s"}, 
{"name": "ファタール", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=1h14m17s"}, 
{"name": "踊", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=1h23m50s"}, 
{"name": "Ready Steady", "url": "https://www.youtube.com/watch?v=k1qjMgd69pI&t=1h31m10s"}]}, 
{"date": "2024/10/31", 
"title": "【#歌枠｜#KARAOKE】🎃Halloween歌枠👻初見さん＆ROM専さん大歓迎～！", 
"theme": ["横枠","Halloween"], 
"url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=0s", 
"songs": [
{"name": "Mrs.Pumpkinの滑稽な夢", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=5m3s"}, 
{"name": "炎と森のカーニバル", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=12m58s"}, 
{"name": "Monster", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=24m52s"}, 
{"name": "ヴィラン", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=37m33s"}, 
{"name": "悪魔の踊り方", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=45m31s"}, 
{"name": "ShadowShadow", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=54m50s"}, 
{"name": "ヴァンパイア", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h2m48s"}, 
{"name": "ゾンビ", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h10m19s"}, 
{"name": "唱", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h20m36s"}, 
{"name": "ディア", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h26m0s"}, 
{"name": "怪物", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h33m10s"}, 
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h47m24s"}, 
{"name": "デビルじゃないもん", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=1h55m38s"}, 
{"name": "Happy Halloween", "url": "https://www.youtube.com/watch?v=2MNy_gk2cfM&t=2h3m18s"}]}, 
{"date": "2024/11/15", 
"title": "【#歌枠｜#KARAOKE】アニソン多め歌枠✨初見さん＆ROM専さん大歓迎～！", 
"theme": ["横枠","アニソン"], 
"url": "https://www.youtube.com/watch?v=R22H81e25P0&t=0s", 
"songs": [
{"name": "Sign", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=5m35s"}, 
{"name": "ニワカ雨ニモ負ケズ", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=12m0s"}, 
{"name": "V", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=19m0s"}, 
{"name": "ゲッタバンバン", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=24m55s"}, 
{"name": "ファイトソング", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=31m43s"}, 
{"name": "ファタール", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=37m25s"}, 
{"name": "勇者", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=43m50s"}, 
{"name": "アイのシナリオ", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=50m15s"}, 
{"name": "ボルテッカー", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=59m25s"}, 
{"name": "１・２・３", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=1h6m0s"}, 
{"name": "ファンサ", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=1h15m25s"}, 
{"name": "晩餐歌", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=1h22m40s"}, 
{"name": "アイドル", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=1h30m55s"}, 
{"name": "怪獣の花唄", "url": "https://www.youtube.com/watch?v=R22H81e25P0&t=1h37m10s"}]}, 
{"date": "2024/12/29", 
"title": "【#歌枠｜#KARAOKE】世にも珍しい夜のチル歌雑", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=0s", 
"songs": [
{"name": "fake face dance music", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=9m58s"}, 
{"name": "スノーマジックファンタジー", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=15m5s"}, 
{"name": "SPECIALZ", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=27m5s"}, 
{"name": "わたしの一番かわいいところ", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=35m30s"}, 
{"name": "ずうっといっしょ！", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=46m30s"}, 
{"name": "レディーレ", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=57m50s"}, 
{"name": "晩餐歌", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h4m20s"}, 
{"name": "サラマンダー", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h13m10s"}, 
{"name": "妄想感傷代償連盟", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h19m5s"}, 
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h34m17s"}, 
{"name": "可不ェイン", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h46m20s"}, 
{"name": "やぎさんゆうびん", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h51m15s"}, 
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=1h52m30s"}, 
{"name": "Supernova", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=2h8m20s"}, 
{"name": "バグ", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=2h18m40s"}, 
{"name": "神のまにまに", "url": "https://www.youtube.com/watch?v=2D-kDXSmHtc&t=2h27m45s"}]}, 

{"date": "2025/01/21", 
"title": "【#歌枠｜#KARAOKE】中低音女子のかっこいい曲多め歌枠🖤", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=0s", 
"songs": [
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=7m30s"},
{"name": "シャンティ", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=12m30s"},
{"name": "ずうっといっしょ！", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=16m55s"},
{"name": "偽物人間40号", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=23m55s"},
{"name": "ジェニ", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=28m58s"},
{"name": "混沌ブギ", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=34m49s"},
{"name": "オーバーライド", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=39m35s"},
{"name": "ULTRA C", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=44m50s"},
{"name": "Loveit?", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=51m45s"},
{"name": "Supernova", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=56m20s"},
{"name": "モニタリング", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=1h1m25s"},
{"name": "ジェヘナ", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=1h6m45s"},
{"name": "CR詠ZY", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=1h13m55s"},
{"name": "サイバーパンクデッドボーイ", "url": "https://www.youtube.com/watch?v=alXvix26Yyw&t=1h19m50s"}]}, 
{"date": "2025/02/13", 
"title": "【#歌耐久枠｜#KARAOKE】登録者600人耐久❕バレンタイン歌枠🍫💭", 
"theme": ["横枠","耐久","バレンタイン"], 
"url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=0s", 
"songs": [
{"name": "小悪魔だってかまわない！", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=9m10s"},
{"name": "かいしんのいちげき！", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=18m18s"},
{"name": "ダーリンダンス", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=28m25s"},
{"name": "ラヴィ", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=35m33s"},
{"name": "ビターチョコデコレーション", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=44m17s"},
{"name": "drop pop candy", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=54m12s"},
{"name": "わたしの一番かわいいところ", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h1m55s"},
{"name": "魔法少女とチョコレゐト", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h14m13s"},
{"name": "携帯恋話", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h20m36s"},
{"name": "心予報", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h28m35s"},
{"name": "スイートマジック", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h37m12s"},
{"name": "可不ェイン", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h48m5s"},
{"name": "可愛くなりたい", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=1h53m28s"},
{"name": "ラブカ？", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h1m20s"},
{"name": "Loveit？", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h6m19s"},
{"name": "ザムザ", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h13m16s"},
{"name": "メンヘラじゃないもん！", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h21m1s"},
{"name": "メランコリック", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h26m13s"},
{"name": "キャットラビング", "url": "https://www.youtube.com/watch?v=Dy1TCr_yqYQ&t=2h31m56s"}]}, 
{"date": "2025/03/01", 
"title": "【#歌枠｜#KARAOKE】夜だけど歌いたくなったのでまったりと🎙", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=0s", 
"songs": [
{"name": "Flyer!", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=8m2s"},
{"name": "ファイアダンス", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=15m1s"},
{"name": "お気に召すまま", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=24m57s"},
{"name": "ファイトソング", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=32m32s"},
{"name": "CR詠ZY", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=39m0s"},
{"name": "月光", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=45m15s"},
{"name": "春を告げる", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=51m53s"},
{"name": "デーモンロード", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=57m56s"},
{"name": "ピッカーン！", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=1h2m12s"},
{"name": "テトリス", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=1h7m40s"},
{"name": "モニタリング", "type": "配信途切れ", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=1h12m43s"},
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=hSJCYkMwolc&t=1h17m42s"}]}, 
{"date": "2025/03/07", 
"title": "【#歌枠｜#KARAOKE】ニーゴ縛りで歌います🎤初見さん大歓迎🫧", 
"theme": ["横枠","プロセカ"], 
"url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=0s", 
"songs": [
{"name": "ロウワー", "type": ["アカペラ "," 途中まで"], "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=3m40s"},
{"name": "ロウワー", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=7m26s"},
{"name": "ヴィラン", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=16m45s"},
{"name": "命ばっかり", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=22m55s"},
{"name": "ボッカデラベリタ", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=30m52s"},
{"name": "ジャックポットサッドガール", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=39m0s"},
{"name": "愛して愛して愛して", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=44m44s"},
{"name": "アイディスマイル", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=51m52s"},
{"name": "トリコロージュ", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=57m28s"},
{"name": "携帯恋話", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=1h4m23s"},
{"name": "バグ", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=1h11m0s"},
{"name": "ノンブレス・オブリージュ", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=1h15m9s"},
{"name": "悔やむと書いてミライ", "url": "https://www.youtube.com/watch?v=HJjn6KjgBGY&t=1h20m45s"}]}, 
{"date": "2025/03/23", 
"title": "【#歌枠｜#KARAOKE】ボカロ多め！日曜お昼のまったり歌枠🫧", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=0s", 
"songs": [
{"name": "きらり", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=9m6s"},
{"name": "potatoになっていく", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=16m43s"},
{"name": "悪魔の踊り方", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=24m20s"},
{"name": "ずうっといっしょ！", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=30m30s"},
{"name": "ファタール", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=35m9s"},
{"name": "Flyer!", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=40m55s"},
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=48m4s"},
{"name": "G4L", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=53m38s"},
{"name": "CH4NGE", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=59m0s"},
{"name": "GETCHA!", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h2m56s"},
{"name": "熱愛フローズン", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h8m27s"},
{"name": "テトリス", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h13m17s"},
{"name": "可不ェイン", "type": "最初エコーなし", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h21m48s"},
{"name": "ジェへナ", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h28m10s"},
{"name": "ダーリンダンス", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h35m10s"},
{"name": "KICK BACK", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h42m54s"},
{"name": "Flos", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h48m8s"},
{"name": "NEO", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h55m19s"},
{"name": "ノンブレス・オブリージュ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=1h59m25s"},
{"name": "回る空うさぎ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h7m35s"},
{"name": "晩餐歌", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h15m26s"},
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h21m56s"},
{"name": "ステラ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h28m40s"},
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h38m54s"},
{"name": "一旦ステイTONIGHT", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h45m38s"},
{"name": "ハム太郎とっとこうた", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=2h52m32s"},
{"name": "ザムザ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=3h5m25s"},
{"name": "怪獣の花唄", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=3h11m33s"},
{"name": "StaRt", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=3h16m58s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=3B4rHPTXg3k&t=3h22m40s"}]}, 
{"date": "2025/04/11", 
"title": "【#歌枠｜#KARAOKE】今週もお疲れ様🫧中低音女子のチル歌枠🎙", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=0s", 
"songs": [
{"name": "Overdose", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=5m14s"},
{"name": "fake face dance music", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=10m15s"},
{"name": "BRAIN", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=15m18s"},
{"name": "虚ろを扇ぐ", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=20m54s"},
{"name": "アイネクライネ", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=26m4s"},
{"name": "水平線", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=32m45s"},
{"name": "ドライフラワー", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=39m33s"},
{"name": "ニア", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=46m11s"},
{"name": "サリシノハラ", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=54m12s"},
{"name": "再会", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h0m5s"},
{"name": "スパークル", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h9m58s"},
{"name": "たばこ", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h18m38s"},
{"name": "snooze", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h26m15s"},
{"name": "花に亡霊", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h32m19s"},
{"name": "帝国少女", "url": "https://www.youtube.com/watch?v=BYuvinJTk4A&t=1h38m27s"}]}, 
{"date": "2025/04/23", 
"title": "【#歌枠｜#KARAOKE】いつもよりゆるめに歌練習🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=0s", 
"songs": [
{"name": "Dec.", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=8m57s"},
{"name": "BRAIN", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=22m1s"},
{"name": "惑星ループ", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=32m55s"},
{"name": "太陽系デスコ", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=38m38s"},
{"name": "Lemon", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=45m51s"},
{"name": "砂の惑星", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=52m37s"},
{"name": "私の一番かわいいところ", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=59m20s"},
{"name": "きゅうくらりん", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h5m35s"},
{"name": "可愛くてごめん", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h14m58s"},
{"name": "ロメオ", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h20m58s"},
{"name": "UNDEAD", "type": "練習", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h28m52s"},
{"name": "百花繚乱", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h34m17s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h40m15s"},
{"name": "ロミオとシンデレラ", "type": "練習", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h46m31s"},
{"name": "ワールドイズマイン", "type": ["練習 "," 1番のみ"], "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h54m16s"},
{"name": "恋愛裁判", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=1h59m49s"},
{"name": "ヴァンパイア", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h10m54s"},
{"name": "神っぽいな", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h18m14s"},
{"name": "フュージョン", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h23m51s"},
{"name": "Supernova", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h28m50s"},
{"name": "Beat Eater", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h37m6s"},
{"name": "Beyond the way", "url": "https://www.youtube.com/watch?v=sB6SdxuQFEk&t=2h44m20s"}]}, 
{"date": "2025/06/01", 
"title": "【#歌枠｜#KARAOKE】みんなひさしぶり～！！すこーしだけ歌うよ🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=0s", 
"songs": [
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=8m34s"},
{"name": "Flyer!", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=15m14s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=34m34s"},
{"name": "ずぅっといっしょ！", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=39m24s"},
{"name": "レクイエム", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=47m4s"},
{"name": "雨とペトラ", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=52m16s"},
{"name": "強風オールバック", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h5m40s"},
{"name": "バグ", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h13m6s"},
{"name": "drop pop candy", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h18m24s"},
{"name": "アンチーユー", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h28m16s"},
{"name": "愛包ダンスホール", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h35m48s"},
{"name": "トリコロージュ", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h45m46s"},
{"name": "CH4NGE", "url": "https://www.youtube.com/watch?v=gpgNBgFPAgQ&t=1h51m45s"}]}, 
{"date": "2025/06/13", 
"title": "【#歌枠｜#KARAOKE】プロセカ ビビバス縛り歌枠🎤🎵", 
"theme": ["横枠","プロセカ"], 
"url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=0s", 
"songs": [
{"name": "阿吽のビーツ", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=4m40s"},
{"name": "絶え間なく藍色", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=11m45s"},
{"name": "シャンティ", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=18m33s"},
{"name": "月光", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=24m25s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=31m26s"},
{"name": "ガランド", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=39m45s"},
{"name": "フラジール", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=46m15s"},
{"name": "ヘイヴン", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=54m5s"},
{"name": "オルターエゴ", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h0m27s"},
{"name": "雨とペトラ", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h6m25s"},
{"name": "チルドレンレコード", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h13m8s"},
{"name": "エゴイスト", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h18m33s"},
{"name": "Pa iii.sensation", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h27m10s"},
{"name": "Awake Now", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h33m55s"},
{"name": "Ready Steady", "url": "https://www.youtube.com/watch?v=CcLJb7fkm2U&t=1h40m7s"}]}, 
{"date": "2025/07/03", 
"title": "【#歌枠 ｜#雑談】少しだけ歌ったり喋ったり💭", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=0s", 
"songs": [
{"name": "Bunny Girl", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=16m51s"},
{"name": "ダーリン", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=34m27s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=45m14s"},
{"name": "大脳的なランデブー", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=49m37s"},
{"name": "ニュートンダンス", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=57m22s"},
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=1h2m37s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=1h11m24s"},
{"name": "ロメオ", "url": "https://www.youtube.com/watch?v=OIwdyODxLSM&t=1h20m6s"}]}, 
{"date": "2025/07/07", 
"title": "【#歌枠 】七夕らしいので歌います🎋", 
"theme": ["横枠","七夕"], 
"url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=0s", 
"songs": [
{"name": "orion", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=6m34s"},
{"name": "灰色と青", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=13m48s"},
{"name": "打上花火", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=22m19s"},
{"name": "いかないで", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=34m19s"},
{"name": "ホシアイ", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=42m23s"},
{"name": "花に亡霊", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=51m4s"},
{"name": "少女レイ", "type": "アカペラ", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=58m53s"},
{"name": "群像夏", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=1h11m54s"},
{"name": "ステラ", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=1h18m34s"},
{"name": "88☆彡", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=1h27m36s"},
{"name": "Stellar Stellar", "url": "https://www.youtube.com/watch?v=I5qfGU6pcqQ&t=1h32m12s"}]}, 
{"date": "2025/07/20", 
"title": "【#歌枠｜#雑談】おともと一緒にゆる歌雑🫧", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=NP26XUACH00&t=0s", 
"songs": [
{"name": "ずうっといっしょ！", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=34m55s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=41m31s"},
{"name": "命ばっかり", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=49m23s"},
{"name": "ひたむきシンデレラ！", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=57m18s"},
{"name": "テレパシ", "type": "配信途切れ", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=1h4m27s"},
{"name": "東京サマーセッション", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=1h11m29s"},
{"name": "アンノウン・マザーグース", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=1h20m2s"},
{"name": "DAYBREAK FRONTLINE", "url": "https://www.youtube.com/watch?v=NP26XUACH00&t=1h34m13s"}]}, 
{"date": "2025/08/15", 
"title": "【耐久歌枠】テーマごとに姿が変わる？！50曲耐久歌枠❕目指せ高評価30＆Ch登録685人🌟", 
"theme": ["横枠","耐久"], 
"url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=0s", 
"songs": [
{"name": "鬼の宴", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=11m20s"},
{"name": "きらり", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=17m26s"},
{"name": "幽霊東京", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=22m23s"},
{"name": "踊り子", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=28m29s"},
{"name": "ウミユリ海底譚", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=34m34s"},
{"name": "ダーリン", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=39m58s"},
{"name": "シャンティ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=44m55s"},
{"name": "LOSER", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=50m7s"},
{"name": "フィクサー", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=56m41s"},
{"name": "フラジール", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h3m48s"},
{"name": "ニア", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h15m14s"},
{"name": "RAIN", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h23m26s"},
{"name": "逆夢", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h31m28s"},
{"name": "少女レイ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h39m4s"},
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h47m54s"},
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=1h58m8s"},
{"name": "雨とペトラ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h5m15s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h13m33s"},
{"name": "エゴロック", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h18m15s"},
{"name": "フォニイ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h23m25s"},
{"name": "ピースサイン", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h40m6s"},
{"name": "ミックスナッツ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h48m0s"},
{"name": "クスシキ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h54m35s"},
{"name": "花になって", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=2h59m17s"},
{"name": "炎", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h5m18s"},
{"name": "アイドル", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h13m26s"},
{"name": "UNDEAD", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h18m54s"},
{"name": "勇者", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h23m41s"},
{"name": "アイのシナリオ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h28m56s"},
{"name": "プライド革命", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h35m24s"},
{"name": "ド屑", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h43m45s"},
{"name": "ラブカ？", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h48m11s"},
{"name": "ギラギラ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h52m31s"},
{"name": "ベノム", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=3h59m13s"},
{"name": "ダーリンダンス", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h5m2s"},
{"name": "妄想感傷代償連盟", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h15m12s"},
{"name": "モニタリング", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h21m29s"},
{"name": "魔法少女とチョコレゐト", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h27m27s"},
{"name": "バグ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h32m24s"},
{"name": "キャットラビング", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h37m1s"},
{"name": "可愛くなりたい", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h43m49s"},
{"name": "Booo!", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h50m43s"},
{"name": "シル・ヴ・プレジデント", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=4h56m43s"},
{"name": "トンデモワンダーズ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h1m35s"},
{"name": "きゅうくらりん", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h7m48s"},
{"name": "強風オールバック", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h13m41s"},
{"name": "サインはB", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h17m41s"},
{"name": "ファンサ", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h23m58s"},
{"name": "clumsy trick", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h33m1s"},
{"name": "Tame-Lie-One-Step", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h41m16s"},
{"name": "Fighting My Way", "url": "https://www.youtube.com/watch?v=XqEDT_UxAUQ&t=5h55m0s"}]}, 
{"date": "2025/09/07－１", 
"title": "【#歌枠】昼下がりのまったり歌枠🫧", 
"theme": ["縦枠","分割"], 
"url": "https://www.youtube.com/watch?v=m9Z_4i1oWYI&t=0s", 
"songs": [
{"name": "プロポーズ", "url": "https://www.youtube.com/watch?v=m9Z_4i1oWYI&t=9m50s"}]}, 
{"date": "2025/09/07－２", 
"title": "【#歌枠】昼下がりのまったり歌枠🫧", 
"theme": ["縦枠","分割"], 
"url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=0s", 
"songs": [
{"name": "Bunny Girl", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=4m52s"},
{"name": "fake face dance music", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=13m1s"},
{"name": "ファタール", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=19m38s"},
{"name": "ずうっといっしょ！", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=24m52s"},
{"name": "アンノウン・マザーグース", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=30m16s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=41m31s"},
{"name": "イケナイ太陽", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=48m5s"},
{"name": "オトナブルー", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=53m59s"},
{"name": "キセキ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h0m13s"},
{"name": "花唄", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h7m43s"},
{"name": "V", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h14m17s"},
{"name": "愛包ダンスホール", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h20m16s"},
{"name": "1・2・3", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h26m28s"},
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h33m43s"},
{"name": "人マニア", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h42m35s"},
{"name": "テトリス", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h46m40s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h51m24s"},
{"name": "ひたむきシンデレラ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=1h56m35s"},
{"name": "リードコントロール", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=2h2m21s"},
{"name": "ザムザ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=2h6m44s"},
{"name": "ジェヘナ", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=2h16m10s"},
{"name": "D/N/A", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=2h23m22s"},
{"name": "NEO", "url": "https://www.youtube.com/watch?v=tr_QGUZ0C-Q&t=2h30m17s"}]}, 
{"date": "2025/10/31", 
"title": "【#歌枠】Halloween歌枠🎃👻久々のお歌枠頑張って歌うよ！", 
"theme": ["横枠","Halloween"], 
"url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=0s", 
"songs": [
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=11m39s"},
{"name": "ヴァンパイア", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=17m47s"},
{"name": "Monster", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=23m33s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=32m14s"},
{"name": "Happy Halloween", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=37m40s"},
{"name": "唱", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=48m26s"},
{"name": "怪物", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=55m30s"},
{"name": "名前のない怪物", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=1h1m48s"},
{"name": "仮装狂騒曲", "url": "https://www.youtube.com/watch?v=0yJcPqhAdPQ&t=1h12m15s"}]}, 
{"date": "2025/12/24", 
"title": "【歌枠｜KARAOKE】高評価20目標🌟今年ラスト歌枠🎧", 
"theme": ["横枠","クリスマス"], 
"url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=0s", 
"songs": [
{"name": "スターライトパレード ", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=12m54s"},
{"name": "クリスマスソング", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=22m37s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=34m52s"},
{"name": "チェリーポップ", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=41m28s"},
{"name": "クスシキ", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=58m54s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h4m29s"},
{"name": "Blue Jeans", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h11m25s"},
{"name": "Tame-Lie-One-Step", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h17m45s"},
{"name": "Fluorite", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h25m23s"},
{"name": "白線", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h32m43s"},
{"name": "世界一可愛い私", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h42m39s"},
{"name": "Booo!", "url": "https://www.youtube.com/watch?v=ae-CPsHXkxw&t=1h58m21s"}]}, 
{"date": "2025/12/29", 
"title": "【歌枠｜KARAOKE】バラードでチル歌枠🌃高評価20目指したい🌟今度こそ今年ラスト歌枠🎙", 
"theme": ["横枠","バラード"], 
"url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=0s", 
"songs": [
{"name": "幽霊東京", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=13m34s"},
{"name": "きらり", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=23m12s"},
{"name": "アイネクライネ", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=33m22s"},
{"name": "Lemon", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=51m41s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=58m39s"},
{"name": "逆夢", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h5m33s"},
{"name": "Pretender", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h13m14s"},
{"name": "群青", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h23m31s"},
{"name": "からくりピエロ", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h31m28s"},
{"name": "回る空うさぎ", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h39m27s"},
{"name": "ハロ／ハワユ", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h44m51s"},
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=J2aZ9Fvo94U&t=1h53m30s"}]}, 

{"date": "2026/01/18", 
"title": "【歌枠｜KARAOKE】高評価20目指したい🌟まったり歌ってくよ～🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=0s", 
"songs": [
{"name": "プロポーズ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=14m5s"}, 
{"name": "BRAIN", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=19m52s"}, 
{"name": "デーモンロード", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=26m18s"},
{"name": "Bunny Girl", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=31m28s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=42m23s"},
{"name": "RPG", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=50m2s"},
{"name": "砂の惑星", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=57m18s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h3m27s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h9m51s"},
{"name": "グッバイ宣言", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h14m30s"},
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h20m52s"},
{"name": "オーバーライド", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h26m33s"},
{"name": "テトリス", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h31m5s"},
{"name": "モニタリング", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h36m13s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h40m53s"},
{"name": "チェリーポップ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h45m46s"},
{"name": "ロミオとシンデレラ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h50m53s"},
{"name": "恋愛裁判", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=1h57m42s"},
{"name": "アイのシナリオ", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=2h3m21s"},
{"name": "プライド革命", "url": "https://www.youtube.com/watch?v=QMQ6X0Wmz50&t=2h11m3s"}]}, 
{"date": "2026/01/27", 
"title": "【歌枠｜KARAOKE】プロセカ ニーゴ縛り歌枠🖤💜", 
"theme": ["横枠","プロセカ"], 
"url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=0s", 
"songs": [
{"name": "ロウワー", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=9m3s"},
{"name": "エンヴィーベイビー", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=18m12s"},
{"name": "神っぽいな", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=22m15s"},
{"name": "フォニイ", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=29m0s"},
{"name": "ボッカデラベリタ", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=34m51s"},
{"name": "妄想感傷代償連盟", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=41m6s"},
{"name": "愛して愛して愛して", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=48m32s"},
{"name": "バグ", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=55m13s"},
{"name": "D/N/A", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=1h1m42s"},
{"name": "ザムザ", "url": "https://www.youtube.com/watch?v=fvYYAQcFi0w&t=1h6m18s"}]}, 
{"date": "2026/02/06", 
"title": "【歌枠】中低音ボイスの短めつまみぐい歌枠🎵", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=0s", 
"songs": [
{"name": "スノーマジックファンタジー", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=13m19s"},
{"name": "RAIN", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=20m51s"},
{"name": "フィクサー", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=30m46s"},
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=41m20s"},
{"name": "レクイエム", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=48m28s"},
{"name": "CH4NGE", "url": "https://www.youtube.com/watch?v=xuRXafbAXS0&t=55m17s"}]}, 
{"date": "2026/02/18", 
"title": "【歌枠｜KARAOKE】病みかわ歌枠🖤🩷高低差すごいセトリらしい💭", 
"theme": ["横枠","バレンタイン","病み"], 
"url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=0s", 
"songs": [
{"name": "ずぅっといっしょ！", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=7m36s"},
{"name": "ビターチョコデコレーション", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=14m34s"},
{"name": "ラヴィ", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=22m43s"},
{"name": "リードコントロール", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=28m48s"},
{"name": "きゅうくらりん", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=33m48s"},
{"name": "ダーリンダンス", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=40m4s"},
{"name": "ベノム", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=48m3s"},
{"name": "魔法少女とチョコレゐト", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=54m1s"},
{"name": "いますぐ輪廻", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=59m29s"},
{"name": "モニタリング", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=1h5m5s"},
{"name": "キャットラビング", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=1h10m25s"},
{"name": "ド屑", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=1h17m44s"},
{"name": "ラブカ？", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=1h24m5s"},
{"name": "バグ", "url": "https://www.youtube.com/watch?v=z1tIQ--tzPU&t=1h34m14s"}]}, 
{"date": "2026/02/22", 
"title": "【歌枠｜KARAOKE】高評価20耐久❕10達成毎に新規お写真公開🤍", 
"theme": ["縦枠","耐久","告知"], 
"url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=0s", 
"songs": [
{"name": "プロポーズ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=18m11s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=25m22s"},
{"name": "BRAIN", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=35m0s"},
{"name": "セレナーデ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=44m6s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=52m37s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=58m51s"},
{"name": "灰色と青", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=1h8m20s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=1h19m8s"},
{"name": "フィクサー", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=1h26m41s"},
{"name": "イイじゃん", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=1h33m39s"},
{"name": "StaRt", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=1h41m17s"},
{"name": "小悪魔だってかまわない！", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h7m22s"},
{"name": "ロメオ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h14m20s"},
{"name": "アイのシナリオ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h24m21s"},
{"name": "プライド革命", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h30m36s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h45m57s"},
{"name": "ひたむきシンデレラ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=2h53m34s"},
{"name": "サンドリヨン", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h1m26s"},
{"name": "太陽系デスコ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h8m22s"},
{"name": "ジェヘナ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h14m19s"},
{"name": "Fighting My Way", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h31m52s"},
{"name": "ピースサイン", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h39m1s"},
{"name": "シャルル", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h46m5s"},
{"name": "ダーリン", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h52m25s"},
{"name": "ラ♪ラ♪ラ♪スイートプリキュア♪", "type": "1番のみ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=3h59m4s"},
{"name": "恋愛裁判", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h11m18s"},
{"name": "夜咄ディセイブ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h18m7s"},
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h23m36s"},
{"name": "NEO", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h29m22s"},
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h36m16s"},
{"name": "ノンブレス・オブリージュ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h45m2s"},
{"name": "エゴロック", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h52m30s"},
{"name": "テレキャスタービーボーイ", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=4h56m51s"},
{"name": "1・2・3", "url": "https://www.youtube.com/watch?v=qzmKkUUQGHU&t=5h12m15s"},]}, 
{"date": "2026/02/27", 
"title": "【歌枠｜KARAOKE】今週もお疲れ様❕まったりチル曲歌う🫧", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=0s", 
"songs": [
{"name": "Overdose", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=13m29s"},
{"name": "Bunny Girl", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=20m39s"},
{"name": "春を告げる", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=29m15s"},
{"name": "踊り子", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=42m55s"},
{"name": "怪獣の花唄", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=52m59s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=59m17s"},
{"name": "馬と鹿", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=1h8m14s"},
{"name": "secret base～君がくれたもの～", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=1h23m4s"},
{"name": "回る空うさぎ", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=1h34m44s"},
{"name": "晩餐歌", "url": "https://www.youtube.com/watch?v=1wm_HGQMPKg&t=1h43m53s"}]}, 
{"date": "2026/03/04", 
"title": "【歌枠｜KARAOKE】懐かしのボカロ縛り❕落ち着く声のまったり歌枠🎙", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=0s", 
"songs": [
{"name": "ウミユリ海底譚", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=12m8s"},
{"name": "アンノウン・マザーグース", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=20m5s"},
{"name": "サンドリヨン", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=32m15s"},
{"name": "恋愛裁判", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=43m13s"},
{"name": "ロミオとシンデレラ", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=49m26s"},
{"name": "ワールドイズマイン", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=56m35s"},
{"name": "メランコリック", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=1h4m40s"},
{"name": "DAYBREAK FRONTLINE", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=1h11m55s"},
{"name": "少女レイ", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=1h16m38s"},
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=vFrGojCSLvA&t=1h24m15s"}]}, 
{"date": "2026/03/16", 
"title": "【歌枠｜KARAOKE】ショートでよく聞く曲多めで歌う🎤落ち着く声のまったり歌枠🫧", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=0s", 
"songs": [
{"name": "プロポーズ", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=11m58s"},
{"name": "睨めっ娘", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=18m56s"},
{"name": "モエチャッカファイア", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=28m43s"},
{"name": "イイじゃん", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=39m3s"},
{"name": "セレナーデ", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=47m18s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=53m1s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=59m11s"},
{"name": "リードコントロール", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h6m58s"},
{"name": "モニタリング", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h17m35s"},
{"name": "チェリーポップ", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h26m25s"},
{"name": "D/N/A", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h30m49s"},
{"name": "いますぐ輪廻", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h34m21s"},
{"name": "ワールドイズマイン", "url": "https://www.youtube.com/watch?v=V4PWh-pKO88&t=1h38m53s"}]}, 
{"date": "2026/03/27", 
"title": "【歌枠｜KARAOKE】告知あり❕落ち着く声のまったり歌枠🎙🫧", 
"theme": ["横枠","告知"], 
"url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=0s", 
"songs": [
{"name": "春を告げる", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=8m3s"},
{"name": "fake face dance music", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=17m50s"},
{"name": "シネマ", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=24m12s"},
{"name": "怪獣の花唄", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=35m45s"},
{"name": "ライラック", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=49m42s"},
{"name": "晴る", "url": "https://www.youtube.com/watch?v=D-Tw7F3jZO0&t=1h0m8s"}]}, 
{"date": "2026/04/16", 
"title": "【歌枠｜KARAOKE】劇場版コナン主題歌限定歌枠👓今年も公開されましたよと！", 
"theme": ["縦枠", "アニソン"], 
"url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=0s", 
"songs": [
{"name": "クロノスタシス", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=11m17s"},
{"name": "BLUE SAPPHIRE", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=24m25s"},
{"name": "美しい鰭", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=36m37s"},
{"name": "永遠の不在証明", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=47m3s"},
{"name": "相思相愛", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=58m7s"},
{"name": "渡月橋～君想ふ～", "url": "https://www.youtube.com/watch?v=FOR9Qk9wyuI&t=1h7m44s"}]}, 
{"date": "2026/04/20", 
"title": "【歌枠｜KARAOKE】新年度応援❕HoneyWorks限定歌枠🐼💓→チャンネル登録800人まで歌う！！", 
"theme": ["縦枠","ハニワ","耐久"], 
"url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=0s", 
"songs": [
{"name": "ロメオ", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=10m25s"},
{"name": "小悪魔だってかまわない！", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=21m18s"},
{"name": "金曜日のおはよう", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=30m1s"},
{"name": "世界は恋に落ちている", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=40m37s"},
{"name": "恋色に咲け", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=50m33s"},
{"name": "可愛くてごめん", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=59m46s"},
{"name": "ファンサ", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=1h9m27s"},
{"name": "決戦スピリット", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=1h19m3s"},
{"name": "アイのシナリオ", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=1h28m0s"},
{"name": "プライド革命", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=1h36m15s"},
{"name": "IRIS OUT", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=1h51m5s"},
{"name": "JANE DOE", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=2h4m9s"},
{"name": "残酷な天使のテーゼ", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=2h12m59s"},
{"name": "オーバーライド", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=2h19m12s"},
{"name": "タッチ", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=2h23m44s"},
{"name": "渡月橋 ～君 想ふ～", "url": "https://www.youtube.com/watch?v=Q-1IW0xtG_E&t=2h31m3s"}]}, 
{"date": "2026/04/21", 
"title": "【歌枠｜KARAOKE】少しだけ歌います！落ち着く声のまったり歌枠🫧", 
"theme": ["縦枠"], 
"url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=0s", 
"songs": [
{"name": "ダイダイダイダイダイキライ", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=8m7s"},
{"name": "馬と鹿", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=13m52s"},
{"name": "セレナーデ", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=22m7s"},
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=29m3s"},
{"name": "ヒバナ", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=36m58s"},
{"name": "テレパシ", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=42m20s"},
{"name": "ワールドイズマイン", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=46m40s"},
{"name": "いますぐ輪廻", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=53m5s"},
{"name": "リードコントロール", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=57m16s"},
{"name": "ギラギラ", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=1h2m44s"},
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=1h12m59s"},
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=8Kr8CmKSVnA&t=1h19m2s"}]}, 
{"date": "2026/04/28", 
"title": "【歌枠｜KARAOKE】落ち着く声の低音チル歌枠🎙🫧", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=0s", 
"songs": [
{"name": "踊り子", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=7m59s"},
{"name": "きらり", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=20m15s"},
{"name": "クロノスタシス", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=31m29s"},
{"name": "プロポーズ", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=43m4s"},
{"name": "ギラギラ", "type": "途中までアカペラ", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=48m59s"},
{"name": "RAIN", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=59m17s"},
{"name": "炎と森のカーニバル", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h9m32s"},
{"name": "Lemon", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h21m7s"},
{"name": "水平線", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h28m12s"},
{"name": "Luna say maybe", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h37m39s"},
{"name": "かわいいだけじゃだめですか？", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h44m55s"},
{"name": "美しい鰭", "url": "https://www.youtube.com/watch?v=PtDmXGQPFwk&t=1h54m38s"}]}, 
{"date": "2026/05/06", 
"title": "【歌枠｜KARAOKE】重大告知あり❕高評価50 or 50曲耐久歌枠🤍🐾", 
"theme": ["縦枠","耐久","告知"], 
"url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=0s", 
"songs": [
{"name": "鬼の宴", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=9m19s"},
{"name": "Bunny Girl", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=15m9s"},
{"name": "小さな恋の歌", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=22m28s"},
{"name": "BRAIN", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=29m59s"},
{"name": "アイデンティティ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=36m56s"},
{"name": "ずぅっといっしょ！", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=45m27s"},
{"name": "マーシャル・マキシマイザー", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=58m27s"},
{"name": "ジャンキーナイトタウンオーケストラ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h3m51s"},
{"name": "はいよろこんで", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h11m15s"},
{"name": "セレナーデ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h17m55s"},
{"name": "Happines", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h24m13s"},
{"name": "Love so sweet", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h31m0s"},
{"name": "世界に一つだけの花", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h40m51s"},
{"name": "orion", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h48m39s"},
{"name": "打上花火", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=1h59m33s"},
{"name": "相思相愛", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h7m27s"},
{"name": "晴る", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h15m17s"},
{"name": "花に亡霊", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h25m5s"},
{"name": "夜明けと蛍", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h31m8s"},
{"name": "シャルル", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h39m36s"},
{"name": "糸", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h45m48s"},
{"name": "サンドリヨン", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=2h56m0s"},
{"name": "RPG", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h4m39s"},
{"name": "Dragon Night", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h11m46s"},
{"name": "スノーマジックファンタジー", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h19m55s"},
{"name": "地球最後の告白を", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h28m0s"},
{"name": "サマータイムレコード", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h33m28s"},
{"name": "NEO", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h41m1s"},
{"name": "ビビデバ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h52m51s"},
{"name": "愛包ダンスホール", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=3h57m33s"},
{"name": "クロノスタシス", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h4m28s"},
{"name": "美しい鰭", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h12m19s"},
{"name": "キミがいれば", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h19m14s"},
{"name": "水平線", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h29m21s"},
{"name": "スパークル", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h39m8s"},
{"name": "仮装狂騒曲", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h49m1s"},
{"name": "Fighting My Way", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=4h54m11s"},
{"name": "ベテルギウス", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h2m8s"},
{"name": "君の知らない物語", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h8m42s"},
{"name": "少女レイ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h17m1s"},
{"name": "イケナイ太陽", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h24m18s"},
{"name": "一旦ステイTONIGHT", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h31m40s"},
{"name": "イイじゃん", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h36m54s"},
{"name": "花唄", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h43m6s"},
{"name": "StaRt", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h48m29s"},
{"name": "ひたむきシンデレラ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=5h55m6s"},
{"name": "だいしきゅーだいしゅき", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=6h0m44s"},
{"name": "ロミオとシンデレラ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=6h6m14s"},
{"name": "ワールドイズマイン", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=6h12m13s"},
{"name": "残酷な天使のテーゼ", "url": "https://www.youtube.com/watch?v=1s0SetK74_Q&t=6h18m57s"}]}, 
{"date": "2026/05/28", 
"title": "【歌枠｜KARAOKE】新衣装で歌います🎀", 
"theme": ["横枠"], 
"url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=0s", 
"songs": [
{"name": "小悪魔だってかまわない！", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=7m58s"},
{"name": "キャットラビング", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=16m31s"},
{"name": "チェリーポップ", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=20m52s"},
{"name": "ラビットホール", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=25m1s"},
{"name": "寝起きヤシの木", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=29m57s"},
{"name": "メランコリック", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=36m22s"},
{"name": "きゅうくらりん", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=43m25s"},
{"name": "ロミオとシンデレラ", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=49m41s"},
{"name": "ワールドイズマイン", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=56m30s"},
{"name": "白い雪のプリンセスは", "url": "https://www.youtube.com/watch?v=MbFYxtfLoyY&t=1h3m33s"}]}

];
